meta_product_name: "ShowTime"
meta_title: "ShowTime - Don't miss the experience"
meta_description: "Achetez des places de cinéma à proximité et
à prix réduits."
meta_image: "logo 1200x630.png" # should exist in `app/assets/images/`
